### ISSUE TITLE
Myddleware 3: How create a new Solution?

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#664]
I want create a new connector to custom service. Now I see the file https://github.com/Myddleware/myddleware/blob/main/src/Manager/SolutionManager.php

- In the version 3 of Myddleware seems Mandatory declase Solutions on the code (Hard-code declared Solutions)
- In the version 2 of Myddleware to have new solution just create a file on the folder (Flexible Solutions loading)

@EstelleMyddleware @Myddleware @simonetravaglini

**Comment by stlgaits** [comment]
Hello @francescobianco in order to add a custom solution, you need to create a custom SolutionManager.php file
To do so, you need to use the Decorator pattern : 
- first create a Custom folder in src folder
- here, add your custom solution file, as well as your custom SolutionManager file
- here is an example of what the src/Custom/Manager/CustomSolutionManager.php file should contain : 

```php
<?php

namespace App\Custom\Manager;

use App\Manager\SolutionManager;

class CustomSolutionManager extends SolutionManager {

}
```

- go to the config/services_custom.yaml file
- in there, there is a commented example of how to declare a custom file, in this case : 
```yaml
App\Custom\Manager\CustomSolutionManager:
    decorates: App\Manager\SolutionManager
    decoration_on_invalid: ignore
    decoration_priority: 1
```
You will need to do the same thing for your custom Solution file.
Hope this is clear, let me know if you have any questions.
